name: Planet
favicon: null
layout_spectrum: 0.5631721781101078
typography_spectrum: 0.02343264943920076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15164319891482592
  lightness: 0.9579917390365154
  saturation: 0.16138086724095047
  rhythmicContrast: 0.10817955946549773
purpose: []
